const languagesArray = {
  "serv-menu": { ua: "Послуги", en: "Services" },
  "portf-menu": { ua: "Портфоліо", en: "Portfolio" },
  "about-menu": { ua: "Про компанію", en: "About company" },
  "cont-menu": { ua: "Контакти", en: "Contacts" },
  "had-btn": { ua: "Зв'язатись з нами", en: "Contact us" },
  "about-design-text": {
    ua: "Процес розробки дизайну UI/UX для веб-сайтів включає аналіз цільової аудиторії та її потреб, створення ідей і концепцій дизайну, розробку прототипів і тестування їх для взаємодії з користувачем, а також визначення колірної палітри, шрифтів та інших елементів дизайну.",
    en: "The process of developing UI/UX design for websites includes analyzing the target audience and their needs, creating ideas and design concepts, developing prototypes and testing them for user experience, as well as defining the color palette, fonts, and other design elements.",
  },
  "about-development-text": {
    ua: "Розробка настільних програм — це процес створення програмного забезпечення для роботи на персональних комп’ютерах, яке встановлюється та виконується без доступу до Інтернету та може мати різні функції, починаючи від обробки тексту та таблиць до розширених графічних можливостей і використання баз даних.",
    en: "Desktop application development is the process of creating software to run on personal computers, which are installed and executed without internet access, and can have various functionalities ranging from processing text and tables to advanced graphical capabilities and use of databases.",
  },
  "about-design-title": { ua: "UI/UX дизайн", en: "UI / UX Design" },
  "about-development-title": { ua: "Розробка додатків для робочого столу", en: "Desktop Application Development" },
  "about-marketing-title": { ua: "Багатоканальний маркетинг", en: "Omnichannel Marketing" },
  "about-marketing-text": {
    ua: "Багатоканальний маркетинг — це маркетингова стратегія, яка передбачає використання різних каналів зв’язку з клієнтами, таких як електронна пошта, соціальні мережі, мобільні додатки, SMS-повідомлення та інші, для створення безперебійного та постійного досвіду взаємодії з брендом незалежно від обраного клієнтом каналу зв’язку. .",
    en: "Omnichannel marketing is a marketing strategy that involves using various communication channels with  customers, such as email, social media, mobile apps, SMS messages, and others, to create a seamless and consistent experience of interacting with a brand regardless of the customer's chosen communication channel.",
  },
  "about-title": { ua: "Про компанію", en: "About company" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
  //   "": { ua: "", en: "" },
};

export default languagesArray;
